services:
  backend:
    build: ./backend
    container_name: mangoscan-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mangoscan-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped